name: AutoMerge

on:
  schedule:
    - cron: '05,17,29,41,53 * * * *'
  pull_request:
    # opened = run when the PR is first opened
    # labeled = run when labels are applied, so that the "Override AutoMerge: name similarity is okay label is respected.
    # synchronize = run when a commit is pushed to the PR
    types: [opened, labeled, synchronize]
  workflow_dispatch:

jobs:
  AutoMerge:
    # Run if the we are not triggered by a label OR we are triggered by a label, and that
    # label is one that affects the execution of the workflow
    # Note: since the label contains a colon, we need to use a workaround like https://github.com/actions/runner/issues/1019#issuecomment-810482716
    # for the syntax to parse correctly.
    if: "${{ github.event.action != 'labeled' || (github.event.action == 'labeled' && (github.event.label.name == 'Override AutoMerge: name similarity is okay' || github.event.label.name == 'Override AutoMerge: package author approved')) }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819 # v1.0.0
      - uses: julia-actions/setup-julia@082493e5c5d32c1fa68c35556429b0f1b2807453 # v1.0.1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies by running Pkg.instantiate()
        run: julia --project=.ci/ -e 'using Pkg; Pkg.instantiate()'
      - name: AutoMerge.pr_check
        env:
          AUTOMERGE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTOMERGE_MERGE_TOKEN: ${{ secrets.TAGBOT_TOKEN }}
          JULIA_DEBUG: AutoMerge
        run: |
          config = AutoMerge.general_registry_config()
          AutoMerge.pr_check(config.registry_config, config.check_pr_config)
        shell: julia --color=yes --project=.ci/ {0}
