[deps]
AutoMerge = "c5732277-7834-41e3-8e1f-5f375898cfe1"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
RegistryCI = "0c95cc5f-2f7e-43fe-82dd-79dbcba86b32"
RegistryInstances = "2792f1a3-b283-48e8-9a74-f99dce5104f3"

[compat]
Documenter = "1"
RegistryInstances = "0.1"

[sources]
AutoMerge = {path = "../AutoMerge.jl"}
RegistryCI = {path = ".."}
